[Default]

[S3]
# S3 호환 서버 주소. AWS 자체를 테스트할 때는 비워 둡니다.
URL =
Port = 80
OldPort = 8080
SSLPort = 443
SignatureVersion = 4
RegionName = ap-northeast-2

[Fixtures]
BucketPrefix = go-
IsSecure = false
NotDelete = false

[Main User]
DisplayName = test1
UserID = 1
Email = test1@test.co.kr
AccessKey =
SecretKey =
KMS =
XAuthToken =

[Alt User]
DisplayName = test2
UserID = 2
Email = test2@test.co.kr
AccessKey =
SecretKey =
KMS =
XAuthToken =

[Backend User]
DisplayName = backend
UserID = backend
Email = backend@test.co.kr
AccessKey =
SecretKey =
KMS =
XAuthToken =
